Repository GoMudEngine/GoMud, pull requests merged in 2025-05, with the labels that each got.

#366 Updated FindNoun to fix issue 356
  internal/rooms/rooms.go
  internal/rooms/rooms_test.go
Labels: bug

#386 Addressing a few typos in the deafen command
  _datafiles/world/empty/templates/admincommands/help/command.deafen.template
Labels: bug

#383 Update GoMud release workflows
  .github/RELEASING.md
  .github/workflows/build-and-release.yml
  .github/workflows/docker-package.yml
  .github/workflows/run-tests.yml
Labels: enhancement

#390 Added tests to character package
  internal/characters/alignment_test.go
  internal/characters/character.go
  internal/characters/character_test.go
  internal/characters/charminfo_test.go
  internal/characters/cooldowns.go
  internal/characters/cooldowns_test.go
  internal/characters/formattedname_test.go
  internal/characters/kdstats_test.go
  internal/characters/mobmastery_test.go
  internal/characters/shop.go
  internal/characters/shop_test.go
  internal/characters/worn_test.go
Labels: enhancement

#391 Added tests to buffs and badinputtracker packages
  internal/badinputtracker/badinputtracker_test.go
  internal/buffs/buffs_test.go
  internal/buffs/buffspec.go
  internal/buffs/buffspec_test.go
Labels: enhancement

#374 Mudlet GMCP Discord Rich Presence functionality
  modules/gmcp/files/data-overlays/config.yaml
  modules/gmcp/files/data-overlays/keywords.yaml
  modules/gmcp/files/data-overlays/mudlet-config.yaml
  modules/gmcp/files/datafiles/templates/help/checkclient.template
  modules/gmcp/files/datafiles/templates/help/client.template
  modules/gmcp/files/datafiles/templates/help/discord.template
  modules/gmcp/files/datafiles/templates/help/mudletmap.template
  modules/gmcp/files/datafiles/templates/help/mudletui.template
  modules/gmcp/gmcp.Mudlet.go
  modules/gmcp/gmcp.go
Labels: enhancement

#387 Markdown
  _datafiles/world/default/ansi-aliases.yaml
  _datafiles/world/default/templates/help/attack.md
  _datafiles/world/default/templates/help/attack.template
  _datafiles/world/empty/ansi-aliases.yaml
  _datafiles/world/empty/templates/help/attack.md
  internal/markdown/README.md
  internal/markdown/ast.go
  internal/markdown/ast_test.go
  internal/markdown/formatter.go
  internal/markdown/formatter_ansitags.go
  internal/markdown/formatter_html.go
  internal/markdown/formatter_remarkdown.go
  internal/markdown/markdown_test.go
  internal/markdown/parser.go
  internal/templates/templates.go
Labels: documentation, enhancement
